# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap
  resolution: 0.05

  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 0.2

  update_frequency: 1.0
  publish_frequency: 1.0

  track_unknown_space: true
  unknown_cost_value: 255

  cost_scaling_factor: 2.0

  plugins:
    - name: static_layer
      type: 'costmap_2d::StaticLayer'
    - name: footprint_layer
      type: 'costmap_2d::FootprintLayer'
    - name: inflation_layer
      type: 'costmap_2d::InflationLayer'

  static_layer:
    enabled  : true
    map_topic: map

  footprint_layer:
    enabled: true

  inflation_layer:
    enabled            : true
    inflation_radius   : 0.81
